### ISSUE TITLE
Multiple backend directories not generally usable

### ISSUE THREAD

**Issue by ivanterrible** [uros-5/jinja-lsp#30]
In the configuration of your `backend` directory (for example using neovim) if you provide multiple directories the LSP will only function if all of the directories exist. If for example you specify:

```lua
backend = { './src_one', './src_two' }
```
If one of those directories does not exist, nothing works. If working on projects that are structured differently you cannot set a global backend value that will work with both.  Given the setting I was expecting that the LSP would look into the specified directory if it is found, otherwise if the directory does not exist ignore it, as opposed to requiring all directories to exist.

**Comment by uros-5** [comment]
Yeah true. I was thinking about moving configuration to: `pyproject.toml`, `cargo.toml`, `jinja-lsp.toml`.
